### ISSUE TITLE
Atom support?

### ISSUE THREAD

**Issue by travischoma** [Slava/tern-meteor#37] opened 2015-07-20 18:44 UTC
I have Ternjs installed in Atom, is there any path to running tern-meteor on Atom?

**Comment by newswim** [comment] 2015-07-30 13:39
Also curious on this, it seems Sublime integration has internal process issues and I've been slowly adopting Atom.

**Comment by Slava** [comment] 2015-07-30 16:48
I think it is described in the readme. Copy the Meteor.js file from this repo into the plugins folder of your tern installation and then enable it in your .tern-project file.

**Comment by angelozerr** [comment] 2015-07-30 21:30
IMHO, I think tern-meteor should be published in the npm registry like other tern plugins https://www.npmjs.com/search?q=tern

So after user could install it with npm install (see for instance https://www.npmjs.com/package/tern-tabris#installation)

I had created a PR for that https://github.com/Slava/tern-meteor/pull/17

**Comment by Slava** [comment] 2015-07-31 00:31
If you guys want to maintain a copy on npm, I have no problems with that, you are free to do this. Closing this issue as it is not a bug.

**Closed by Slava** 2015-07-31 00:31 UTC

**Comment by ferhtgoldaraz** [comment] 2015-11-07 18:22
I've published a fork of this on npm. Anything I should know, tell me.
